listen = "localhost:8080"

storage_dir = "/mnt/selfstream-public/"

base_url = "https://streaming.afilini.com/"
cdn_url = "https://videocdn.afilini.com/"

redis_server = "redis://127.0.0.1/"

stat_url = "http://localhost/stat"

[btcpay]
key = ""
url = ""
merchant = ""
webhook = ""
